# Generated by Django 2.2 on 2020-08-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_advert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='desription',
            new_name='description',
        ),
    ]
