# Generated by Django 2.2 on 2020-08-02 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200801_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
