# Generated by Django 2.2 on 2020-08-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200802_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='price',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.ManyToManyField(blank=True, related_name='heighest_bid', to='auctions.Advert'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
