# Generated by Django 2.2 on 2020-08-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200802_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='advertisement',
        ),
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, related_name='advert', to='auctions.Advert'),
            preserve_default=False,
        ),
    ]
