# Generated by Django 2.2 on 2020-08-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='advertisement',
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='auctions.Bid'),
        ),
    ]
