# Generated by Django 2.2 on 2020-08-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200803_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ad', to='auctions.Bid'),
        ),
    ]
