# Generated by Django 2.2 on 2020-08-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200803_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='advertisement',
            field=models.ManyToManyField(related_name='bids', to='auctions.Advert'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='auctions.Advert'),
        ),
    ]
