# Generated by Django 2.2 on 2020-08-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_advert_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='advertisement',
        ),
        migrations.AddField(
            model_name='bid',
            name='advertisement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bids', to='auctions.Advert'),
            preserve_default=False,
        ),
    ]
