# Generated by Django 2.2 on 2020-08-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200803_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Advert'),
        ),
    ]
