# Generated by Django 2.2 on 2020-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200803_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
