# Generated by Django 2.2 on 2020-08-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='status',
            new_name='active',
        ),
    ]
