# Generated by Django 2.2 on 2020-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200804_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.URLField(default='Image Place'),
            preserve_default=False,
        ),
    ]
